# Generated by Django 5.0.1 on 2024-02-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(verbose_name='region')),
                ('title', models.TextField(verbose_name='title')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.TextField(verbose_name='phone')),
                ('score', models.TextField(verbose_name='score')),
                ('open_time', models.TextField(verbose_name='open_time')),
                ('comment1', models.TextField(verbose_name='comment1')),
                ('comment2', models.TextField(verbose_name='comment2')),
                ('comment3', models.TextField(verbose_name='comment3')),
            ],
            options={
                'db_table': 'bar',
                'indexes': [models.Index(fields=['region'], name='bar_region_c4c379_idx')],
            },
        ),
        migrations.CreateModel(
            name='DrinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(verbose_name='region')),
                ('title', models.TextField(verbose_name='title')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.TextField(verbose_name='phone')),
                ('score', models.TextField(verbose_name='score')),
                ('open_time', models.TextField(verbose_name='open_time')),
                ('comment1', models.TextField(verbose_name='comment1')),
                ('comment2', models.TextField(verbose_name='comment2')),
                ('comment3', models.TextField(verbose_name='comment3')),
            ],
            options={
                'db_table': 'drink',
                'indexes': [models.Index(fields=['region'], name='drink_region_d1f22c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(verbose_name='region')),
                ('title', models.TextField(verbose_name='title')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.TextField(verbose_name='phone')),
                ('score', models.TextField(verbose_name='score')),
                ('open_time', models.TextField(verbose_name='open_time')),
                ('comment1', models.TextField(verbose_name='comment1')),
                ('comment2', models.TextField(verbose_name='comment2')),
                ('comment3', models.TextField(verbose_name='comment3')),
            ],
            options={
                'db_table': 'food',
                'indexes': [models.Index(fields=['region'], name='food_region_75e9b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(verbose_name='region')),
                ('title', models.TextField(verbose_name='title')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.TextField(verbose_name='phone')),
                ('score', models.TextField(verbose_name='score')),
                ('open_time', models.TextField(verbose_name='open_time')),
                ('comment1', models.TextField(verbose_name='comment1')),
                ('comment2', models.TextField(verbose_name='comment2')),
                ('comment3', models.TextField(verbose_name='comment3')),
            ],
            options={
                'db_table': 'hotel',
                'indexes': [models.Index(fields=['region'], name='hotel_region_0aa6e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(verbose_name='region')),
                ('title', models.TextField(verbose_name='title')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.TextField(verbose_name='phone')),
                ('score', models.TextField(verbose_name='score')),
                ('open_time', models.TextField(verbose_name='open_time')),
                ('comment1', models.TextField(verbose_name='comment1')),
                ('comment2', models.TextField(verbose_name='comment2')),
                ('comment3', models.TextField(verbose_name='comment3')),
            ],
            options={
                'db_table': 'restaurant',
                'indexes': [models.Index(fields=['region'], name='restaurant_region_1e5fea_idx')],
            },
        ),
        migrations.CreateModel(
            name='SightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(verbose_name='region')),
                ('title', models.TextField(verbose_name='title')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.TextField(verbose_name='phone')),
                ('score', models.TextField(verbose_name='score')),
                ('open_time', models.TextField(verbose_name='open_time')),
                ('comment1', models.TextField(verbose_name='comment1')),
                ('comment2', models.TextField(verbose_name='comment2')),
                ('comment3', models.TextField(verbose_name='comment3')),
            ],
            options={
                'db_table': 'sight',
                'indexes': [models.Index(fields=['region'], name='sight_region_7419b0_idx')],
            },
        ),
    ]
